theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
cursorline = true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "separator", "spinner", "file-name"]
right = ["diagnostics", "separator", "file-type", "separator", "position"]

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
# TODO: there must be a builtin way to do this?
# for moving selected lines up/down
C-j = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'add_newline_below', 'move_line_down', 'replace_with_yanked']
C-k = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'move_line_up', 'add_newline_above', 'move_line_up', 'replace_with_yanked']

